### ISSUE TITLE
Please see posted issue

### ISSUE THREAD

**Issue by treyhamilton** [aephidayatuloh/rpubs#3]
Hi,

I have everything updated and installed 100% however, I was trying to use this to extract a file that I found and received the following output:

Please wait...
This depends on your internet connection speed and 'size' of content.

Error in str_match(css, el_re) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/stringi/R/stringi.rdb' is corrupt
In addition: Warning messages:
1: In str_match(css, el_re) : restarting interrupted promise evaluation
2: In str_match(css, el_re) : internal error -3 in R_decompress1

**Comment by aephidayatuloh** [comment]
Hi @treyhamilton, 
Thank you and highly appreciate for your question.

Based on the error, I believe this related to the {stringi} package.

I see here https://stackoverflow.com/questions/39560808/rendering-an-rmd-fails-because-stringr-rdb-is-corrupt with similar error about {stringi} package. The problem can be solved with restart the R session.
